import { AppState, Status, Priority, TimelineEvent } from "./types";
import { subHours, subMinutes } from "date-fns";

const now = new Date();

const t = (hoursAgo: number, minutesAgo: number = 0) =>
  subMinutes(subHours(now, hoursAgo), minutesAgo).toISOString();

export const seedData: AppState = {
  currentDoctorId: "D-101",
  doctors: {
    "D-101": { id: "D-101", name: "Dr. Sarah Chen", department: "Internal Medicine" },
    "D-102": { id: "D-102", name: "Dr. James Wilson", department: "Cardiology" },
    "D-103": { id: "D-103", name: "Dr. Priya Patel", department: "General Surgery" },
  },
  departments: {
    "DEP-1": { id: "DEP-1", name: "Pharmacy" },
    "DEP-2": { id: "DEP-2", name: "X-Ray Lab" },
    "DEP-3": { id: "DEP-3", name: "Pathology Lab" },
    "DEP-4": { id: "DEP-4", name: "Radiology" },
    "DEP-5": { id: "DEP-5", name: "Blood Bank" },
    "DEP-6": { id: "DEP-6", name: "Cardiology" },
  },
  patients: {
    "P-1042": { id: "P-1042", name: "Robert Miller", age: 64, gender: "Male", ward: "Ward 3B", bed: "Bed 12" },
    "P-1043": { id: "P-1043", name: "Aisha Sharma", age: 42, gender: "Female", ward: "Ward 2A", bed: "Bed 04" },
    "P-1044": { id: "P-1044", name: "Marcus Johnson", age: 28, gender: "Male", ward: "ER", bed: "Bed 01" },
    "P-1045": { id: "P-1045", name: "Eleanor Davis", age: 82, gender: "Female", ward: "ICU", bed: "Bed 08" },
    "P-1046": { id: "P-1046", name: "David Kim", age: 55, gender: "Male", ward: "Ward 4C", bed: "Bed 22" },
  },
  investigations: {
    "INV-001": {
      id: "INV-001",
      patientId: "P-1042",
      orderedByDoctorId: "D-101",
      type: "Lipid Panel",
      notes: "Routine check, fasting 12h",
      priority: "Routine",
      departmentId: "DEP-3",
      status: "Reviewed by Doctor",
      resultNotes: "LDL elevated at 160 mg/dL. HDL 45 mg/dL. Triglycerides 150 mg/dL.",
      technician: "Tech A. Smith",
      timeline: [
        { stage: "Ordered", timestamp: t(24), actor: "Dr. Sarah Chen" },
        { stage: "Sent to Department", timestamp: t(23, 45), actor: "Dr. Sarah Chen" },
        { stage: "In Progress", timestamp: t(22), actor: "Tech A. Smith" },
        { stage: "Result Ready", timestamp: t(20), actor: "Tech A. Smith" },
        { stage: "Reviewed by Doctor", timestamp: t(2), actor: "Dr. Sarah Chen" },
      ],
    },
    "INV-002": {
      id: "INV-002",
      patientId: "P-1044",
      orderedByDoctorId: "D-103",
      type: "CT Scan",
      notes: "Rule out appendicitis",
      priority: "Stat",
      departmentId: "DEP-4",
      status: "Result Ready",
      resultNotes: "No evidence of acute appendicitis. Mild thickening of terminal ileum.",
      technician: "Tech B. Jones",
      timeline: [
        { stage: "Ordered", timestamp: t(3), actor: "Dr. Priya Patel" },
        { stage: "Sent to Department", timestamp: t(2, 55), actor: "Dr. Priya Patel" },
        { stage: "In Progress", timestamp: t(2, 40), actor: "Tech B. Jones" },
        { stage: "Result Ready", timestamp: t(0, 15), actor: "Tech B. Jones" },
      ],
    },
    "INV-003": {
      id: "INV-003",
      patientId: "P-1045",
      orderedByDoctorId: "D-102",
      type: "ECG",
      notes: "Patient reporting chest pain",
      priority: "Stat",
      departmentId: "DEP-6",
      status: "In Progress",
      technician: "Tech C. Williams",
      timeline: [
        { stage: "Ordered", timestamp: t(1), actor: "Dr. James Wilson" },
        { stage: "Sent to Department", timestamp: t(0, 50), actor: "Dr. James Wilson" },
        { stage: "In Progress", timestamp: t(0, 20), actor: "Tech C. Williams" },
      ],
    },
    "INV-004": {
      id: "INV-004",
      patientId: "P-1043",
      orderedByDoctorId: "D-101",
      type: "Urine Culture",
      notes: "Suspected UTI",
      priority: "Routine",
      departmentId: "DEP-3",
      status: "Sent to Department",
      technician: "Tech D. Brown",
      timeline: [
        { stage: "Ordered", timestamp: t(5), actor: "Dr. Sarah Chen" },
        { stage: "Sent to Department", timestamp: t(4, 30), actor: "Dr. Sarah Chen" },
      ],
    },
    "INV-005": {
      id: "INV-005",
      patientId: "P-1046",
      orderedByDoctorId: "D-102",
      type: "Blood Test",
      notes: "CBC and BMP",
      priority: "Urgent",
      departmentId: "DEP-3",
      status: "Ordered",
      timeline: [
        { stage: "Ordered", timestamp: t(0, 5), actor: "Dr. James Wilson" },
      ],
    },
    "INV-006": {
      id: "INV-006",
      patientId: "P-1042",
      orderedByDoctorId: "D-101",
      type: "X-Ray",
      notes: "Chest AP/Lat",
      priority: "Routine",
      departmentId: "DEP-2",
      status: "Reviewed by Doctor",
      resultNotes: "Clear lungs. No acute cardiopulmonary process.",
      technician: "Tech E. Davis",
      timeline: [
        { stage: "Ordered", timestamp: t(48), actor: "Dr. Sarah Chen" },
        { stage: "Sent to Department", timestamp: t(47), actor: "Dr. Sarah Chen" },
        { stage: "In Progress", timestamp: t(46), actor: "Tech E. Davis" },
        { stage: "Result Ready", timestamp: t(45), actor: "Tech E. Davis" },
        { stage: "Reviewed by Doctor", timestamp: t(24), actor: "Dr. Sarah Chen" },
      ],
    },
    "INV-007": {
      id: "INV-007",
      patientId: "P-1044",
      orderedByDoctorId: "D-103",
      type: "Ultrasound",
      notes: "Abdominal right lower quadrant",
      priority: "Stat",
      departmentId: "DEP-4",
      status: "In Progress",
      technician: "Tech F. Miller",
      timeline: [
        { stage: "Ordered", timestamp: t(4), actor: "Dr. Priya Patel" },
        { stage: "Sent to Department", timestamp: t(3, 50), actor: "Dr. Priya Patel" },
        { stage: "In Progress", timestamp: t(3, 30), actor: "Tech F. Miller" },
      ],
    },
    "INV-008": {
      id: "INV-008",
      patientId: "P-1045",
      orderedByDoctorId: "D-102",
      type: "Blood Test",
      notes: "Cardiac enzymes (Troponin)",
      priority: "Stat",
      departmentId: "DEP-3",
      status: "Result Ready",
      resultNotes: "Troponin I < 0.04 ng/mL (Normal)",
      technician: "Tech G. Wilson",
      timeline: [
        { stage: "Ordered", timestamp: t(1, 30), actor: "Dr. James Wilson" },
        { stage: "Sent to Department", timestamp: t(1, 20), actor: "Dr. James Wilson" },
        { stage: "In Progress", timestamp: t(1, 10), actor: "Tech G. Wilson" },
        { stage: "Result Ready", timestamp: t(0, 5), actor: "Tech G. Wilson" },
      ],
    }
  },
};
